site_name: RDK Service Documentation

theme:
  name: material
  features:
    - toc.follow
    - content.tabs
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 2-2

nav:
  - Home: index.md
  - RDKShell: RDKShell.md
  - UserSettings: UserSettings.md
